version: "3.8"

services:
  app_blue:
    image: "${BLUE_IMAGE}"
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${APP_PORT}
    ports:
      - "${BLUE_PORT}:${APP_PORT}"
    networks:
      - appnet

  app_green:
    image: "${GREEN_IMAGE}"
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${APP_PORT}
    ports:
      - "${GREEN_PORT}:${APP_PORT}"
    networks:
      - appnet

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - app_blue
      - app_green
    ports:
      - "${NGINX_PORT}:80"
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - APP_PORT=${APP_PORT}
    volumes:
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh:ro
    command: ["/bin/sh", "/docker-entrypoint.sh"]
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
